[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E203"]
[tool.pytest.ini_options]
addopts = "-q --cov=src --cov-report=xml --cov-report=term-missing"
