name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure test/coverage tools are available even if not in requirements.txt
          pip install pytest pytest-cov

      - name: Lint (ruff)
        run: |
          ruff --version
          ruff check .

      - name: Test (pytest) with coverage
        run: |
          pytest -q \
            --maxfail=1 --disable-warnings \
            --cov=. \
            --cov-report=xml:coverage.xml \
            --cov-report=term-missing

      - name: Verify coverage file exists
        run: ls -lh coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: unittests
          verbose: true
          fail_ci_if_error: false

